kennellog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from user import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('user/', include ('user.urls')),
    path('panels/', include ('panels.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panels/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User
from .views import mainEmployeePage, mainFacilityPage, employeeDogPanel, EmpDashDogDetailView, employeeAdminPanel, employeeReviewReservationsPanel, BoardingResApprovalRedirect, EmployeeTaskCompleteRedirect, employeeTaskPanel, TaskCreateView, TaskUpdateView, TaskDeleteView, employeePlaygroundView
from communication.views import AdminMessageCreateView

urlpatterns = [
    path ('employee-home/', mainEmployeePage, name='employee-home'),
    path ('employee-playground-view/', employeePlaygroundView, name='employee-playground-view'),
    path ('employee-dog/', employeeDogPanel, name='employee-dog'),
    path ('employee-dog/<slug:slug>/', EmpDashDogDetailView.as_view(), name='employee-dog-detail'),
    path ('employee-admin/review-reservations/', employeeReviewReservationsPanel, name='employee-admin-review-reservations'),
    path ('employee-admin/review-reservations/<slug:slug>/approve', BoardingResApprovalRedirect.as_view(), name='board-res-approval'),
    path ('employee-tasks/', employeeTaskPanel, name='employee-tasks'),
    path ('employee-task-create/', TaskCreateView.as_view(), name='employee-task-create-view'),
    path ('employee-tasks/<slug:slug>/edit/', TaskUpdateView.as_view (), name='employee-task-edit'),
    path ('employee-tasks/<slug:slug>/mark-complete', EmployeeTaskCompleteRedirect.as_view (), name='employee-task-mark-completed'),
    path ('employee-tasks/<slug:slug>/delete/', TaskDeleteView.as_view (), name='employee-task-delete'),
    path ('facility-home/', mainFacilityPage, name='facility-home'),
    path ('add-facility-admin-message/', AdminMessageCreateView.as_view(), name='create-admin-message'),
]

user/urls.py
from .views import ProfileDetail, DogProfileDetail, DogProfileUpdateView, DogCreateView
from scheduling.views import BoardingReservationCreateView, BoardingReservationUpdateView, BoardingReservationDeleteView
from django.urls import path
from django.contrib.auth.models import User

urlpatterns = [
    path ('create-dog/', DogCreateView.as_view (), name='dog-create'),
    path ('dog/<slug:slug>/', DogProfileDetail.as_view (), name='dog-detail,'),
    path ('dog/<slug:slug>/edit/', DogProfileUpdateView.as_view (), name='dog-update'),
    path ('boarding-request/', BoardingReservationCreateView.as_view (template_name='scheduling/boarding_request_form.html'), name='boarding-request'),
    path ('boarding-request/<slug:slug>/edit/', BoardingReservationUpdateView.as_view (), name='boarding-request-update'),
    path ('boarding-request/<slug:slug>/delete/', BoardingReservationDeleteView.as_view (), name='boarding-request-delete'),
    path ('<slug:slug>/', ProfileDetail.as_view (template_name='user/profile_detail.html'), name='user-profile'),
]

panels/models.py
from django.db import models
from django.contrib.auth.signals import user_logged_in
from django.shortcuts import render, get_object_or_404
from scheduling.models import EmployeeTask, BoardingReservation
from datetime import date, datetime, timedelta

def assign_tasks (sender, user, request, **kwargs):
    if user.profile.employee_role == 0:
        walkTasks = EmployeeTask.objects.filter (date=date.today ()).filter (facility=user.profile.facilityWorksAt).filter (title__contains='Walk')
        playTasks = EmployeeTask.objects.filter (date=date.today ()).filter (facility=user.profile.facilityWorksAt).filter (title__contains='Playtime with')

        activeBoardingReservations = BoardingReservation.objects.filter (startDate__lte=date.today()).filter (endDate__gte=date.today()).filter (facility=user.profile.facilityWorksAt).filter (approved=True)
        morningTime = datetime.strptime ("08:00:00", '%H:%M:%S')
        afternoonTime = datetime.strptime ("12:00:00", '%H:%M:%S')
        eveningTime = datetime.strptime ("19:00:00", '%H:%M:%S')

        for reservation in activeBoardingReservations:
            pottyTasksToday = EmployeeTask.objects.filter (reservationBoarding=reservation).filter (date=date.today ()).filter (title__contains='break')

            if pottyTasksToday.count() == 3:
                task1 = pottyTasksToday [0]
                task2 = pottyTasksToday [1]
                task3 = pottyTasksToday [2]
                task1.startTime = morningTime
                task1.endTime = morningTime + timedelta(minutes=5)
                task1.employee = user
                morningTime = task1.endTime
                task1.save ()
                task2.startTime = afternoonTime
                task2.endTime = afternoonTime + timedelta(minutes=5)
                task2.employee = user
                afternoonTime = task2.endTime
                task2.save ()
                task3.startTime = eveningTime
                task3.endTime = eveningTime + timedelta(minutes=5)
                task3.employee = user
                eveningTime = task3.endTime
                task3.save ()
            elif pottyTasksToday.count() == 1:
                if date.today ()==reservation.startDate:
                    task1 = pottyTasksToday [0]
                    task1.startTime = eveningTime
                    task1.endTime = eveningTime + timedelta(minutes=5)
                    task1.employee = user
                    morningTime = task1.endTime
                    task1.save ()
                if date.today ()==reservation.endDate:
                    task1 = pottyTasksToday [0]
                    task1.startTime = morningTime
                    task1.endTime =  + timedelta(minutes=5)
                    task1.employee = user
                    morningTime = task1.endTime
                    task1.save ()

        startSchedulingAt = datetime.strptime ("09:00:00", '%H:%M:%S')

        for task in playTasks:
            task.startTime = startSchedulingAt
            task.endTime = timedelta(minutes=10) + startSchedulingAt
            task.employee = user
            startSchedulingAt = timedelta(minutes=10) + startSchedulingAt
            task.save ()

        startSchedulingAt = datetime.strptime ("16:00:00", '%H:%M:%S')

        for task in walkTasks:
            task.startTime = startSchedulingAt
            task.endTime = startSchedulingAt + timedelta(minutes=15)
            task.employee = user
            startSchedulingAt = task.endTime
            task.save ()
    

user_logged_in.connect (assign_tasks)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from PIL import Image
from django.urls import reverse

#///////////////////////////////////////////////////////////////////////
USER_TYPES = (
    (0,"Facility"),
    (1,"Employee"),
    (2,"Customer"),
)

USER_PRONOUNS = (
    (0,"they/them"),
    (1,"she/her"),
    (2,"he/him"),
)

WEEKDAYS = (
    (0,_("Sunday")),
    (1,_("Monday")),
    (2,_("Tuesday")),
    (3,_("Wednesday")),
    (4,_("Thursday")),
    (5,_("Friday")),
    (6,_("Saturday")),
)

DOG_GENDERS = (
    (0,"Female, Intact"),
    (1,"Male, Intact"),
    (2,"Female, Spayed"),
    (3,"Male, Neutered"),
)

EMPLOYEE_TASK_ROLES = (
    (0,"Dog Exerciser"),
    (1,"Management"),
    (2,"Trainer"),
    (3,"Playtime Handler"),
    (4,"Kennel Wrangler"),
    (5,"No Role"),
)


#///////////////////////////////////////////////////////////////////////
class Profile (models.Model):
    user = models.OneToOneField (User, on_delete=models.CASCADE)
    user_type = models.IntegerField (choices=USER_TYPES, default=0)
    slug = models.SlugField (max_length=200, unique=True)
    birthdate = models.DateField (null=True)
    pronouns = models.IntegerField (choices=USER_PRONOUNS, default=0)
    biography = models.TextField (max_length=1000, null=True, blank=True)
    address = models.CharField (max_length=500, null=True, blank=True)
    phone_number = models.CharField (max_length=20, null=True, blank=True)
    profile_image = models.ImageField (default='default.jpg', upload_to='profile_pics')
    banner_image = models.ImageField (default='defaultbanner.jpg', upload_to='user_gallery') # for facility
    first_name = models.CharField (max_length=200, null=True, blank=True)
    last_name = models.CharField (max_length=200, null=True, blank=True)
    facilityWorksAt = models.ForeignKey (User, default=None, blank=True, null=True, related_name='facility', on_delete=models.CASCADE)
    numOfKennels = models.IntegerField (null=True, blank=True)
    numOfPlaygrounds = models.IntegerField (null=True, blank=True)
    employee_role = models.IntegerField (choices=EMPLOYEE_TASK_ROLES, default=5)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save (self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open (self.profile_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail (output_size)
            img.save (self.profile_image.path)
        
        #if user_type == 0:
            # todo: create kennels for num of kennels


class HoursAvailable (models.Model):
    business = models.ForeignKey (User, on_delete=models.CASCADE)
    weekday = models.IntegerField (choices=WEEKDAYS)
    from_hour = models.TimeField ()
    to_hour = models.TimeField ()

    """
    class Meta:
        ordering = ('weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')
    
    def __unicode__ (self):
        return u'%s: %s - %s' % (self.get_weekday_display(),
                                 self.from_hour, self.to_hour)
    """

class EmergencyContact (models.Model):
    user = models.ForeignKey (User, on_delete=models.CASCADE)
    first_name = models.CharField (max_length=200)
    last_name = models.CharField (max_length=200)
    phone_number = models.CharField (max_length=20)
    relationship = models.CharField (max_length=100)

class DogProfile (models.Model):
    owner = models.ForeignKey (User, on_delete=models.CASCADE, related_name='dogs')
    slug = models.SlugField (max_length=200, unique=True, default="dog")
    fullName = models.CharField (max_length=400)
    nickName = models.CharField (max_length=300)
    image = models.ImageField (default='default.jpg', upload_to='profile_pics')
    gender = models.IntegerField (choices=DOG_GENDERS)
    birthdate = models.DateField (null=True)
    breed = models.CharField (max_length=400)
    weight = models.IntegerField ()
    foodBrand = models.CharField (max_length=400, blank=True)
    microchipNum = models.IntegerField (blank=True, null=True)
    feedTime1 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt1 = models.IntegerField (blank=True, null=True)
    feedTime2 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt2 = models.IntegerField (blank=True, null=True)
    feedTime3 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt3 = models.IntegerField (blank=True, null=True)

    def __str__ (self):
        return self.nickName
    
    def get_absolute_url (self):
        return reverse ('dog-detail', kwargs={'slug': self.slug})

panels/templates/panels/employee_admin_panel.html
{% extends "panels/employee_panel_base.html" %}
{% block info %}
    <div class="row">
        <div class="col" align="center"><a href="{% url 'employee-admin-review-reservations' %}"><button class="btn button5">Boarding Reservations</button></a></div>
        <div class="col" align="center"><a href="#"><button class="btn button5">Daycare Reservations</button></a></div>
    </div>
    {% block minipanel %}{% endblock minipanel %}
{% endblock info %}

panels/templates/panels/employee_dog_detail_view.html
{% extends "mainsite/base.html" %}
{% block content %}

{% endblock content %}

panels/templates/panels/employee_dog_panel.html
{% extends "panels/employee_panel_base.html" %}
{% block info %}
                <div class="row" style="margin-top: 30px;">
                    <div class="col">
                        <div class="row-md-3">
                            <div class="content-section" style="margin-bottom: 0px; padding-left: 0px; padding-top: 2px; padding-bottom: 2px; background-color: #ba4bd6; outline-color: #ba4bd6;">
                                <h4 style="margin-left: 10px; margin-bottom: 0px; margin-top: 0px; color: white;">DAYCARE</h4>
                            </div>
                        </div>
                        {% for reservation in daycaredogs %}
                            <div class="row-md-3">
                                <div class="content-section" style="margin-bottom: 0px; padding-left: 2px;">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img class="account-img" style="height: 100px; width: 100px; margin-top: 2px; margin-bottom: 2px; margin-left:8px;" src="{{ reservation.dog.image.url }}">
                                        </div>
                                        <div class="col">
                                            <h4 style="margin-bottom: 3px;">{{ reservation.dog.nickName }}
                                                {% if reservation.dog.gender == 1 or reservation.dog.gender == 3 %}
                                                    <a align="right" href="#" class="fa fa-mars" style="margin-left: 80px; color: #afaeae;"></a>
                                                {% else %}
                                                    <a align="right" href="#" class="fa fa-venus" style="margin-left: 90px; margin-right: 0px; color: #afaeae;"></a>
                                                {% endif %}
                                            </h4>
                                            <h6 style="color: #929292; margin-top: 2px; margin-bottom: 0px;">{{ reservation.dropoffTime|date:"g:i A" }} - {{ reservation.pickupTime|date:"g:i A" }}</h6>
                                            <p style="margin-top: 2px;"></br>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col">
                        <div class="row-md-3">
                            <div class="content-section" style="margin-bottom: 0px; padding-left: 0px; padding-top: 2px; padding-bottom: 2px; background-color: #ba4bd6; outline-color: #ba4bd6;">
                                <h4 style="margin-left: 10px; margin-bottom: 0px; margin-top: 0px; color: white;">BOARDING</h4>
                            </div>
                        </div>
                        {% for reservation in boardingdogs %}
                            <div class="row-md-3">
                                <div class="content-section" style="margin-bottom: 0px; padding-left: 2px;">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img class="account-img" style="height: 100px; width: 100px; margin-top: 2px; margin-bottom: 2px; margin-left:8px;" src="{{ reservation.dog.image.url }}">
                                        </div>
                                        <div class="col">
                                            <h4 style="margin-bottom: 3px;"><a href="{% url 'employee-dog-detail' reservation.dog.slug %}" style="color: black;">{{ reservation.dog.nickName }}</a>
                                                {% if reservation.dog.gender == 1 or reservation.dog.gender == 3 %}
                                                    <a align="right" href="#" class="fa fa-mars" style="margin-left: 70px; color: #afaeae;"></a>
                                                {% else %}
                                                    <a align="right" href="#" class="fa fa-venus" style="margin-left: 100px; margin-right: 0px; color: #afaeae;"></a>
                                                {% endif %}
                                            </h4>
                                            <h6 style="color: #929292; margin-top: 2px; margin-bottom: 0px;">{{ reservation.startDate|date:"M j" }} - {{ reservation.endDate|date:"M j" }}</h6>
                                            <p style="margin-top: 2px;"> </br>
                                                </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
{% endblock info %}

panels/templates/panels/employee_mainpage.html
{% extends "panels/employee_panel_base.html" %}
{% block info %}
<div class="col-md-12">
    <row>
        <div class="row" style="margin-top: 20px;">
            {% for kennel in rangeOne %}
                {% if kennel.currentlyOccupied %}
                <div class="col" style="border: 1px solid #2e2e2e;">
                    <h6 style="color: #a0a0a0">{{ kennel.kennelNum }}</h6>
                    <img class="rounded-circle account-img" style="height: 100px; width: 100px; margin-left: auto; margin-right: auto; display: block; margin-bottom: 2px;" src="{{ kennel.currentReservation.dog.image.url }}">
                    <h5 align="center">{{ kennel.currentReservation.dog.nickName }}</h5>
                    {% if kennel.currentReservation.status == 0 %}
                        <div class="row" style="background: lightgreen; border: 1px solid rgb(110, 199, 110); height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                            <a class="fa fa-check" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                        </div>
                    {% elif kennel.currentReservation.status == 1 %}
                        <div class="row" style="background: #f5d273; border: 1px solid #bd9f4f; height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                            <a class="fa fa-warning" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                        </div>
                    {% elif kennel.currentReservation.status == 2 %}
                        <div class="row" style="background: #f57373; border: 1px solid #d15c5c; height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                            <a class="fa fa-warning" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                        </div>
                    {% endif %}
                </div>
                {% else %}
                    <div class="col" style="border: 1px solid #2e2e2e; padding-bottom:125px; padding-left: 5px">
                            <h6 style="color: #a0a0a0">{{ kennel.kennelNum }}</h6>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row" style="border: 1px solid #2e2e2e; padding:20px;">
            {% for user in kennelWrangler %}
                <div class="col">
                    <img class="rounded-circle account-img" style="height: 100px; width: 100px; margin-bottom: 2px;" src="{{ user.profile_image.url }}">
                    <h5 style="margin-left: 25px;">{{ user.first_name }}</h5>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            {% for kennel in rangeTwo %}
                {% if kennel.currentlyOccupied %}
                    <div class="col" style="border: 1px solid #2e2e2e;">
                        <h6 style="color: #a0a0a0">{{ kennel.kennelNum }}</h6>
                        <img class="rounded-circle account-img" style="height: 100px; width: 100px; margin-left: auto; margin-right: auto; display: block; margin-bottom: 2px;" src="{{ kennel.currentReservation.dog.image.url }}">
                        <h5 align="center">{{ kennel.currentReservation.dog.nickName }}</h5>
                        {% if kennel.currentReservation.status == 0 %}
                            <div class="row" style="background: lightgreen; border: 1px solid rgb(110, 199, 110); height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                                <a class="fa fa-check" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                            </div>
                        {% elif kennel.currentReservation.status == 1 %}
                            <div class="row" style="background: #f5d273; border: 1px solid #bd9f4f; height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                                <a class="fa fa-warning" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                            </div>
                        {% elif kennel.currentReservation.status == 2 %}
                            <div class="row" style="background: #f57373; border: 1px solid #d15c5c; height: 30px; width: 60px; margin-left: 26px; margin-bottom: 20px;">
                                <a class="fa fa-warning" style="color: white; margin-top: 5px; margin-left: 22px;"></a>
                            </div>
                        {% endif %}
                    </div>
                {% else %}
                    <div class="col" style="border: 1px solid #2e2e2e; padding-bottom:125px; padding-left: 5px">
                            <h6 style="color: #a0a0a0">{{ kennel.kennelNum }}</h6>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
</div>
{% endblock info %}

panels/templates/panels/employee_playground_view.html
{% extends "panels/employee_panel_base.html" %}
{% block info %}
<div class="col-md-12">
    {% for playground in playgrounds %}
        <h4 style="margin-top: 50px;"">Playground {{ playground.playgroundNum }}</h4>
        <div class="row" style="border: 1px solid #2e2e2e; padding: 10px;">
            {% if playground.employee %}
                    <div class="row">
                        <div class="col" style="margin-top: 10px; margin-right: 40px;">
                            <img class="rounded-circle account-img" style="height: 100px; width: 100px; margin-left: auto; margin-right: auto; display: block; margin-bottom: 2px;" src="{{ playground.employee.profile.profile_image.url }}">
                            <h5 align="center">{{ playground.employee.profile.first_name }}</h5>
                        </div>
                    </div>
            {% endif %}
            <div class="row">
                {% for reservation in reservations %}
                    {% if reservation.playground == playground %}
                        <div class="col" style="margin-top: 10px;">
                            <img class="rounded-circle account-img" style="height: 100px; width: 100px; margin-left: auto; margin-right: auto; display: block; margin-bottom: 2px;" src="{{ reservation.dog.image.url }}">
                            <h5 align="center">{{ reservation.dog.nickName }}</h5>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>
{% endblock info %}

panels/templates/panels/employee_review_res_list.html
{% extends "panels/employee_admin_panel.html" %}
{% block minipanel %}
                <div class="row">
                    <div class="col">
                        <div class="row-md-3">
                            <div class="content-section" style="margin-top: 5px; margin-bottom: 5px; padding-left: 0px; padding-top: 2px; padding-bottom: 2px; background-color: #ba4bd6; outline-color: #ba4bd6;">
                                <h5 style="margin-left: 10px; margin-bottom: 0px; margin-top: 0px; color: white;">PENDING APPROVAL</h5>
                            </div>
                        </div>
                        {% for reservation in boardingReservations %}
                            <div class="row-md-9">
                                <div class="content-section" style="margin-bottom: 0px; padding-left: 2px;">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img class="account-img" style="height: 100px; width: 100px; margin-top: 2px; margin-bottom: 2px; margin-left:8px;" src="{{ reservation.dog.image.url }}">
                                        </div>
                                        <div class="col-md-10">
                                            <h4 style="margin-bottom: 3px;"><a href="{% url 'employee-dog-detail' reservation.dog.slug %}" style="color: black;">{{ reservation.dog.nickName }}</a>
                                            </h4>
                                            <h6 style="color: #929292; margin-top: 2px; margin-bottom: 0px;">{{ reservation.dropoffTime }} {{ reservation.startDate|date:"M j, Y" }} - {{ reservation.pickupTime }} {{ reservation.endDate|date:"M j, Y" }}</h6>
                                            <p style="margin-top: 2px;">
                                                {{ reservation.dog.breed }} | {{ reservation.dog.get_gender_display }} | DOB: {{ reservation.dog.birthdate }} | {{ reservation.dog.weight }} lbs</br>
                                                <b>Owner:</b> {{ reservation.dog.owner.profile.first_name }} {{ reservation.dog.owner.profile.last_name }} | {{ reservation.dog.owner.profile.phone_number }}</br>
                                                {% if reservation.notes %}
                                                    <b>Notes from Owner:</b> {{ reservation.notes }}
                                                {% endif %}
                                            </p>
                                            <a align="right" href="{{ reservation.get_kudos_url }}" class="fa fa-check" style="margin-left: 500px; color: green;"></a>
                                            <a align="right" href="#" class="fa fa-times" style="margin-left: 10px; color: red;"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="row-md-3">
                            <div class="content-section" style="margin-top: 5px; margin-bottom: 5px; padding-left: 0px; padding-top: 2px; padding-bottom: 2px; background-color: #ba4bd6; outline-color: #ba4bd6;">
                                <h5 style="margin-left: 10px; margin-bottom: 0px; margin-top: 0px; color: white;">UPCOMING RESERVATIONS</h5>
                            </div>
                        </div>
                        {% for reservation in upcomingReservations %}
                            <div class="row-md-9">
                                <div class="content-section" style="margin-bottom: 0px; padding-left: 2px;">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img class="account-img" style="height: 100px; width: 100px; margin-top: 2px; margin-bottom: 2px; margin-left:8px;" src="{{ reservation.dog.image.url }}">
                                        </div>
                                        <div class="col-md-10">
                                            <h4 style="margin-bottom: 3px;"><a href="{% url 'employee-dog-detail' reservation.dog.slug %}" style="color: black;">{{ reservation.dog.nickName }}</a>
                                            </h4>
                                            <h6 style="color: #929292; margin-top: 2px; margin-bottom: 0px;">{{ reservation.dropoffTime }} {{ reservation.startDate|date:"M j, Y" }} - {{ reservation.pickupTime }} {{ reservation.endDate|date:"M j, Y" }}</h6>
                                            <p style="margin-top: 2px;">
                                                {{ reservation.dog.breed }} | {{ reservation.dog.get_gender_display }} | DOB: {{ reservation.dog.birthdate }} | {{ reservation.dog.weight }} lbs</br>
                                                <b>Owner:</b> {{ reservation.dog.owner.profile.first_name }} {{ reservation.dog.owner.profile.last_name }} | {{ reservation.dog.owner.profile.phone_number }}</br>
                                                {% if reservation.notes %}
                                                    <b>Notes from Owner:</b> {{ reservation.notes }}
                                                {% endif %}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
{% endblock minipanel %}

panels/templates/panels/employee_task_update_view.html
{% extends "panels/employee_panel_base.html" %}
{% block info %}
    <div class="row">
        <div class="col" align="center"><a href="{% url 'employee-task-create-view' %}"><button class="btn button5">Add Task</button></a></div>
    </div>
    <div class="row" style="margin-top: 10px;">
        <div class="col">
            <div class="row-md-9">
                <div class="content-section" style="margin-bottom: 0px; padding-left: 20px;">
                    <div class="row">
                        <div class="col-md-10">
                            <p style="margin-bottom: 5px;"></p>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <legend class="border-bottom mb-4">Edit Task</legend>
                                    {{ form|crispy }}
                                </fieldset>
                                <div class="form-group">
                                    <button class="btn btn-outline-info" type="submit">Save</button>
                                </div>
                            </form>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock info %}