kennellog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from user import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('user/', include ('user.urls')),
    path('panels/', include ('panels.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from .views import ProfileDetail, DogProfileDetail, DogProfileUpdateView, DogCreateView
from scheduling.views import BoardingReservationCreateView, BoardingReservationUpdateView, BoardingReservationDeleteView
from django.urls import path
from django.contrib.auth.models import User

urlpatterns = [
    path ('create-dog/', DogCreateView.as_view (), name='dog-create'),
    path ('dog/<slug:slug>/', DogProfileDetail.as_view (), name='dog-detail,'),
    path ('dog/<slug:slug>/edit/', DogProfileUpdateView.as_view (), name='dog-update'),
    path ('boarding-request/', BoardingReservationCreateView.as_view (template_name='scheduling/boarding_request_form.html'), name='boarding-request'),
    path ('boarding-request/<slug:slug>/edit/', BoardingReservationUpdateView.as_view (), name='boarding-request-update'),
    path ('boarding-request/<slug:slug>/delete/', BoardingReservationDeleteView.as_view (), name='boarding-request-delete'),
    path ('<slug:slug>/', ProfileDetail.as_view (template_name='user/profile_detail.html'), name='user-profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from PIL import Image
from django.urls import reverse

#///////////////////////////////////////////////////////////////////////
USER_TYPES = (
    (0,"Facility"),
    (1,"Employee"),
    (2,"Customer"),
)

USER_PRONOUNS = (
    (0,"they/them"),
    (1,"she/her"),
    (2,"he/him"),
)

WEEKDAYS = (
    (0,_("Sunday")),
    (1,_("Monday")),
    (2,_("Tuesday")),
    (3,_("Wednesday")),
    (4,_("Thursday")),
    (5,_("Friday")),
    (6,_("Saturday")),
)

DOG_GENDERS = (
    (0,"Female, Intact"),
    (1,"Male, Intact"),
    (2,"Female, Spayed"),
    (3,"Male, Neutered"),
)

EMPLOYEE_TASK_ROLES = (
    (0,"Dog Exerciser"),
    (1,"Management"),
    (2,"Trainer"),
    (3,"Playtime Handler"),
    (4,"Kennel Wrangler"),
    (5,"No Role"),
)


#///////////////////////////////////////////////////////////////////////
class Profile (models.Model):
    user = models.OneToOneField (User, on_delete=models.CASCADE)
    user_type = models.IntegerField (choices=USER_TYPES, default=0)
    slug = models.SlugField (max_length=200, unique=True)
    birthdate = models.DateField (null=True)
    pronouns = models.IntegerField (choices=USER_PRONOUNS, default=0)
    biography = models.TextField (max_length=1000, null=True, blank=True)
    address = models.CharField (max_length=500, null=True, blank=True)
    phone_number = models.CharField (max_length=20, null=True, blank=True)
    profile_image = models.ImageField (default='default.jpg', upload_to='profile_pics')
    banner_image = models.ImageField (default='defaultbanner.jpg', upload_to='user_gallery') # for facility
    first_name = models.CharField (max_length=200, null=True, blank=True)
    last_name = models.CharField (max_length=200, null=True, blank=True)
    facilityWorksAt = models.ForeignKey (User, default=None, blank=True, null=True, related_name='facility', on_delete=models.CASCADE)
    numOfKennels = models.IntegerField (null=True, blank=True)
    numOfPlaygrounds = models.IntegerField (null=True, blank=True)
    employee_role = models.IntegerField (choices=EMPLOYEE_TASK_ROLES, default=5)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save (self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open (self.profile_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail (output_size)
            img.save (self.profile_image.path)
        
        #if user_type == 0:
            # todo: create kennels for num of kennels


class HoursAvailable (models.Model):
    business = models.ForeignKey (User, on_delete=models.CASCADE)
    weekday = models.IntegerField (choices=WEEKDAYS)
    from_hour = models.TimeField ()
    to_hour = models.TimeField ()

    """
    class Meta:
        ordering = ('weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')
    
    def __unicode__ (self):
        return u'%s: %s - %s' % (self.get_weekday_display(),
                                 self.from_hour, self.to_hour)
    """

class EmergencyContact (models.Model):
    user = models.ForeignKey (User, on_delete=models.CASCADE)
    first_name = models.CharField (max_length=200)
    last_name = models.CharField (max_length=200)
    phone_number = models.CharField (max_length=20)
    relationship = models.CharField (max_length=100)

class DogProfile (models.Model):
    owner = models.ForeignKey (User, on_delete=models.CASCADE, related_name='dogs')
    slug = models.SlugField (max_length=200, unique=True, default="dog")
    fullName = models.CharField (max_length=400)
    nickName = models.CharField (max_length=300)
    image = models.ImageField (default='default.jpg', upload_to='profile_pics')
    gender = models.IntegerField (choices=DOG_GENDERS)
    birthdate = models.DateField (null=True)
    breed = models.CharField (max_length=400)
    weight = models.IntegerField ()
    foodBrand = models.CharField (max_length=400, blank=True)
    microchipNum = models.IntegerField (blank=True, null=True)
    feedTime1 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt1 = models.IntegerField (blank=True, null=True)
    feedTime2 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt2 = models.IntegerField (blank=True, null=True)
    feedTime3 = models.TimeField (auto_now=False, blank=True, null=True)
    feedAmt3 = models.IntegerField (blank=True, null=True)

    def __str__ (self):
        return self.nickName
    
    def get_absolute_url (self):
        return reverse ('dog-detail', kwargs={'slug': self.slug})

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


USER_TYPES = (
    (0,"Facility"),
    (1,"Employee"),
    (2,"Customer"),
)

#///////////////////////////////////////////////////////////////////////
class UserRegisterForm (UserCreationForm):
    email = forms.EmailField ()
    user_type = forms.ChoiceField (choices=USER_TYPES, help_text='Account Type')

    class Meta:
        model = User
        fields = ['user_type', 'username', 'email', 'password1', 'password2']

class UserUpdateForm (forms.ModelForm):
    email = forms.EmailField ()

    class Meta:
        model = User
        fields = ['username', 'email']

class FacilityProfileUpdateForm (forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'biography', 'address', 'phone_number', 'profile_image', 'banner_image']

class EmployeeProfileUpdateForm (forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['facilityWorksAt', 'first_name', 'last_name', 'birthdate', 'pronouns', 'biography', 'address', 'phone_number', 'profile_image', 'banner_image']

class CustomerUpdateForm (forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'pronouns', 'biography', 'address', 'phone_number', 'profile_image', 'banner_image']

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile, DogProfile
from .forms import UserRegisterForm, UserUpdateForm, FacilityProfileUpdateForm, EmployeeProfileUpdateForm, CustomerUpdateForm
from django.views.generic import DetailView, CreateView, UpdateView
from django.http import Http404
from django.utils.text import slugify


def register (request):
    if request.method == 'POST':
        form = UserRegisterForm (request.POST)
        if form.is_valid ():
            user = form.save ()
            user.profile.user_type = form.cleaned_data.get ('user_type')
            user.profile.slug = form.cleaned_data.get ('username')
            user.save ()
            username = form.cleaned_data.get('username')
            messages.success (request, f'Account created for {username}! You are now able to log in.')
            return redirect ('login')
    else:
        form = UserRegisterForm ()
    return render (request, 'user/register.html', {'form': form})

class ProfileDetail (DetailView):
    model = Profile
    template = 'user/profile.html'
    def get_context_data (self, **kwargs):
        context = super(ProfileDetail, self).get_context_data(**kwargs)
        context['dogs'] = DogProfile.objects.filter (owner=self.object.user)
        context['coworkers'] = Profile.objects.filter (facilityWorksAt=self.object.user.profile.facilityWorksAt).exclude (user=self.object.user)
        return context
    
    def form_valid (self, form):
        form.instance.slug = slugify (self.request.user.username)
        return super ().form_valid (form)

@login_required
def profile (request):
    if request.method == 'POST':
        u_form = UserUpdateForm (request.POST, instance=request.user)
        p_form = FacilityProfileUpdateForm (request.POST, request.FILES, instance=request.user.profile)
        
        if u_form.is_valid () and p_form.is_valid ():
            u_form.save ()
            p_form.save ()
            messages.success (request, f'Account updated!')
            return redirect ('profile')

    else:
        u_form = UserUpdateForm (instance=request.user)
        p_form = FacilityProfileUpdateForm (instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'user/profile_update.html', context)


class DogProfileDetail (DetailView):
    model = DogProfile
    template = 'user/dog_profile.html'
    def get_context_data (self, **kwargs):
        context = super (DogProfileDetail, self).get_context_data(**kwargs)
        return context
    
    def form_valid (self, form):
        form.instance.slug = slugify (self.request.user.username + " " + form.instance.nickname)
        return super ().form_valid (form)

class DogCreateView (LoginRequiredMixin, CreateView):
    model = DogProfile
    fields = ['owner', 'image', 'slug', 'fullName', 'nickName', 'gender', 'birthdate', 'breed', 'weight', 'foodBrand', 'microchipNum', 'feedTime1', 'feedAmt1', 'feedTime2', 'feedAmt2', 'feedTime3', 'feedAmt3']

    def from_valid (self, form):
        form.instance.slug = slugify (self.request.user.username + " " + form.instance.nickname)
        form.instance.owner = self.request.user
        return super ().form_valid (form)

class DogProfileUpdateView (LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = DogProfile
    fields = ['image', 'fullName', 'nickName', 'gender', 'birthdate', 'breed', 'weight', 'foodBrand', 'microchipNum', 'feedTime1', 'feedAmt1', 'feedTime2', 'feedAmt2', 'feedTime3', 'feedAmt3']

    def from_valid (self, form):
        form.instance.slug = slugify (self.request.user.username + " " + form.instance.nickname)
        return super ().form_valid (form)

    def test_func (self):
        dog = self.get_object()
        if self.request.user == dog.owner:
            return True
        return False

user/templates/user/dog_confirm_delete.html
{% extends "mainsite/base.html" %}

{% block content %}
<div class="col-md-12">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete a Dog</legend>
                <h2>Are you sure you want to delete {{ object.nickName }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'dog-detail' object.slug %}">Cancel</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/dogprofile_detail.html
{% extends "mainsite/base.html" %}
{% block content %}
    <div class="col-md-13">
        <div class="content-section">
            <div class="media">
                <div class="col-md-2" align="center">
                    <img class="rounded-circle account-img" src="{{ object.image.url }}">
                </div>

                <div class="media-body">
                    <h2 class="account-heading">{{ object.nickName }}</h2>
                    <p class="text-secondary">
                        Dog * {{ object.fullName }}</br>
                        {{ object.breed }}
                    </p>
                    
                    <p class="text-secondary">{{ object.user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="content-section">
                <h3>Owner</h3>
                <a href="{% url 'user-profile' object.owner.profile.slug %}">{{ object.owner.profile.first_name }} {{ object.owner.profile.last_name }}</a>
                <p class="article-content">
                    {{ object.owner.profile.phone_number }}</p>
                <p class="article-content">{{ object.owner.profile.address }}</p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="content-section">
                <h3>Information</h3>
            </div>
        </div>
    </div>

{% endblock content %}

user/templates/user/dogprofile_form.html
{% extends "mainsite/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-12">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add a Dog</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/login.html
{% extends "mainsite/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                <center>Don't have an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a></center>
            </small>
        </div>
    </div>
{% endblock content %}

user/templates/user/logout.html
{% extends "mainsite/base.html" %}
{% block content %}
    <h2>You have been logged out.</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <center><a href="{% url 'login' %}">Log In Again</a></center>
        </small>
    </div>
{% endblock content %}

user/templates/user/profile_detail.html
{% extends "mainsite/base.html" %}
{% block content %}

{% if object.user.profile.user_type == 0 %}
    <div class="col-md-13">
        <div class="content-section">
            <div class="media">
                <div class="col-md-2" align="center">
                    <img class="rounded-circle account-img" src="{{ object.user.profile.profile_image.url }}">
                </div>

                <div class="media-body">
                    <h2 class="account-heading">{{ object.user.profile.first_name }}</h2>
                    <p class="text-secondary">
                        facility * {{ object.user.username }}</br>
                    </p>
                    
                    <p class="text-secondary">{{ object.user.profile.biography }}</p>
                </div>
                <small style="float:right">
                    <a href="#"><button class="btn button6">Book Daycare Appointment</button></a>
                    <a href="{% url 'boarding-request' %}"><button class="btn button6">Book Boarding Appointment</button></a>
                </small>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="content-section">
                <h4>Contact</h4>
                <p class="article-content">{{ object.user.profile.phone_number }}</p>
                <p class="article-content">{{ object.user.profile.address }}</p>
                <h6>Hours</h6>
                <p class="text-secondary">Sun 8:00 AM - 12:30 PM <br>
                    Mon 6:30 AM - 6:30 PM <br>
                    Tue 6:30 AM - 6:30 PM <br>
                    Wed 6:30 AM - 6:30 PM <br>
                    Thu 6:30 AM - 6:30 PM <br>
                    Fri 6:30 AM - 6:30 PM <br>
                    Sat 8:00 AM - 5:30 PM
                </p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="content-section">
                <h3>Facility</h3>
            </div>
        </div>
    </div>

{% elif object.user.profile.user_type == 1 %}
    <div class="col-md-13">
        <div class="content-section">
            <div class="media">
                <div class="col-md-2" align="center">
                    <img class="rounded-circle account-img" src="{{ object.user.profile.profile_image.url }}">
                </div>

                <div class="media-body">
                    <h2 class="account-heading">{{ object.user.profile.first_name }} {{ object.user.profile.last_name }}</h2>
                    <p class="text-secondary">
                        employee * {{ object.user.username }}</br>
                    </p>
                    
                    <p class="text-secondary">{{ object.user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="content-section">
                <h4>Contact</h4>
                <p class="article-content">{{ object.user.profile.phone_number }}</p>
                <p class="article-content">{{ object.user.profile.address }}</p>
                <hr class="solid">
                <h4>Work Preferences</h4>
                <h6>Roles</h6>
                <p>{{ object.user.profile.get_employee_role_display }}</p>
                <h6>Hours</h6>
                <p class="text-secondary">Sun 8:00 AM - 12:30 PM <br>
                    Mon 6:30 AM - 6:30 PM <br>
                    Tue 6:30 AM - 6:30 PM <br>
                    Wed 6:30 AM - 6:30 PM <br>
                    Thu 6:30 AM - 6:30 PM <br>
                    Fri 6:30 AM - 6:30 PM <br>
                    Sat 8:00 AM - 5:30 PM
                </p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="content-section">
                <h3>Facility</h3>
                <hr class="solid">
                <div class="row">
                    <div class="col-md-3">
                        <img class="rounded-circle account-img" src="{{ object.user.profile.facilityWorksAt.profile.profile_image.url }}">
                    </div>
                    <div class="col">
                        <a href="{% url 'user-profile' object.user.profile.facilityWorksAt.profile.slug %}"><h4>{{ object.user.profile.facilityWorksAt.profile.first_name }} - {{ object.user.profile.facilityWorksAt.username }}</h4></a>
                        <p>{{ object.user.profile.facilityWorksAt.profile.address }}</br>
                            {{ object.user.profile.facilityWorksAt.profile.phone_number }}</br>
                            Manager:
                        </p>
                    </div>
                </div>
                <hr class="solid">
                <h3>Coworkers</h3>
                <hr class="solid">
                {% for user in coworkers %}
                    <div class="row">
                        <div class="col-md-3">
                            <img class="rounded-circle account-img" src="{{ user.profile_image.url }}">
                        </div>
                        <div class="col">
                            <a href="{% url 'user-profile' user.slug %}"><h4>{{ user.first_name }} {{user.last_name}} - {{ user.user.username }}</h4></a>
                            <p>{{ user.address }}</br>
                                {{user.phone_number }}</br>
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% elif object.user.profile.user_type == 2 %}
    <div class="col-md-13">
        <div class="content-section">
            <div class="media">
                <div class="col-md-2" align="center">
                    <img class="rounded-circle account-img" src="{{ object.user.profile.profile_image.url }}">
                </div>

                <div class="media-body">
                    <h2 class="account-heading">{{ object.user.profile.first_name }} {{ object.user.profile.last_name }}</h2>
                    <p class="text-secondary">
                        customer * {{ object.user.username }}</br>
                    </p>
                    
                    <p class="text-secondary">{{ object.user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="content-section">
                <h4>Contact</h4>
                <p class="article-content">{{ object.user.profile.phone_number }}</p>
                <p class="article-content">{{ object.user.profile.address }}</p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="content-section">
                <h3>Dogs</h3>
                <div class="row">
                {% for dog in dogs %}
                    <div class="col-md-6">
                        <div class="content-section">
                            <img class="rounded-circle account-img" src="{{ dog.image.url }}">
                            {% if dog.owner == user or user.user_type == 1 %}
                                <a style="float:right" href="#" class="fa fa-trash"></a>
                                <a style="float:right" href="{% url 'dog-update' dog.slug %}" class="fa fa-pencil"></a>
                            {% endif %}
                            <h4>{{ dog.nickName }}</h4>
                            <p class="article-content">{{ dog.breed }} | {{ dog.birthdate }}</p>
                            <div>
                              </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'dog-create' %}">Add Dog</a>
            </div>
        </div>
    </div>

{% endif %}

{% endblock content %}

user/templates/user/profile_update.html
{% extends "mainsite/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-12">
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.profile_image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">facility</p>
            </div>
        </div>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/register.html
{% extends "mainsite/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}